### ISSUE TITLE
No dungeonworld-fr.js in your archive

### ISSUE THREAD

**Issue by ZolOnTheNet** [YanKlInnomme/FoundryVTT-dungeonworld-fr#4]
Thank for the work !
My english is no fluent
no file dungeonworld-fr.js in the archive zip and when you try to install.

Merci pour le travail de traduction !
Quand j'installe le module ou que je télécharge le .zip, il manque le fichier dungeonworld-fr.js 
Bonne continuation et encore merci du travail !

**Comment by YanKlInnomme** [comment]
Merci pour le retour, effectivement il y avait un loupé dans l'archive. J'ai corrigé la chose et mis en place une nouvelle version 2.1.1
